name: Deploy to cPanel
on:
  push:
    branches:
      - ZheeSchool
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Deploy to cPanel
      uses: Samkirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp_username: ${{ secrets.ZHEESCHOOL_FTP_USERNAME }}
        ftp_password: ${{ secrets.ZHEESCHOOL_FTP_PASSWORD }}
        ftp-server: ${{ secrets.ZHEESCHOOL_FTP_SERVER }}
