name: Deploy to cPanel
on:
  push:
    branches:
      - ZheeSchool
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Deploy to cPanel
      uses: Samkirkland/FTP-Deploy-Action@3.1.1
      with:
        CPANEL_USERNAME: ${{ secrets.ZHEESCHOOL_FTP_USERNAME }}
        CPANEL_PASSWORD: ${{ secrets.ZHEESCHOOL_FTP_PASSWORD }}
        CPANEL_DOMAIN: ${{ secrets.ZHEESCHOOL_FTP_SERVER }}
